- name: Run pytest
  uses: pavelzw/pytest-action@v2.2.0
  with:
      verbose: true
      emoji: false
      job-summary: false
      custom-arguments: '-q'
      click-to-expand: true
      report-title: 'Test Report'
