class Deployment:
    """
    Structure of the schema defining deployment
    """

    # required defining data
    name: deploy_city 
    flow_id: UUID
    entrypoint: prefect/flows.py:api_call
    path: /Users/almarojas/Desktop/Documents/Projects/DataEngineering/citybike-dataEng/

    # workflow scheduling and parametrization
    parameters: dict = None
    parameter_openapi_schema: dict = None
    schedules:
        interval: 600
        timezone: America/Chicago 
    paused: bool = False
    trigger: Trigger = None

    # metadata for bookkeeping
    version: str = None
    description: str = None
    tags: list = None

    # worker-specific fields
    work_pool_name: str = None
    work_queue_name: str = None
    infra_overrides: dict = None
    pull_steps: dict = None