name: Pylint

on: [push]

jobs:
    pytest:
      permissions:
        contents: 'read'
        id-token: 'write'
  
      runs-on: ubuntu-22.04
      steps:
          - name: Checkout 
            uses: actions/checkout@v4
  
          - name: Set up Python
            uses: 'actions/setup-python@v5.0.0'
            with:
              python-version: 3.11.7
  
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest==8.1.1
              pip install pytest-cov==5.0.0
  
          - name: Google Auth
            id: auth
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  
          - name: Run Tests
            run: |
              pytest --cov=streamlit_app tests/ -v
